// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfjjybzxmmryixcszumy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamp5Ynp4bW1yeWl4Y3N6dW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTAxNzQsImV4cCI6MjA2ODgyNjE3NH0.DnUApvgaxp9IpE8mB7zjIe5Ek8w32yyrZQwRY09FqJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});